vich_uploader:
    db_driver: orm
    mappings:
        film_images:
            uri_prefix: /images/films
            upload_destination: '%kernel.project_dir%/public/images/films'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
